# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./TCBApp
      run: docker-compose build
    - name: Deploy
      working-directory: ./TCBApp
      run: |
            docker-compose down
            docker-compose up -d
